version: 2.0

workflows: 
   version: 2
   build-deploy:
     jobs:
       - build
       - deploy:
           requires:
             - build
             - hold
          context: aws-context   
           filters:
             branches:
               only: master 



jobs:
  build:
    docker:
      - image: circleci/node:12.18.2
    working_directory: ~/repo
    steps:
      - checkout
      # Bundle install dependencies
      - run: npm install 
      - run: npm run test:unit
      - run : npm run build

      deploy:
        docker: # Specify executor for running deploy job
          - image: circleci/node:12.18.2 # Specify docker image to use
        steps:
          - run: # Install the AWS CLI if it is not already included in the docker image
              name: Install awscli 
              command: sudo pip install awscli
          - run: # Deploy to S3 using the sync command
              name: Deploy to S3
              command: aws s3 sync ./dist/ s3://cbarahona.com
       