version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.18.2
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install 
      - run: npm run test:unit
      - run: npm run build

      - persist_to_workspace:
        root: .
        paths:
          - .

  deploy:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Upload file to S3
          command: aws s3 sync ./dist/ s3://cbarahona.com

workflows: 
  version: 2
  build:
    jobs:
      - build
      - hold: 
          type: approval 
          filters:
            branches:
              only: master 
      - deploy:
          requires:
            - build
            - hold
          context: aws
          filters:
            branches:
              only: master 
         